# Generated by Django 3.0.6 on 2020-05-07 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variant',
            old_name='height',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='width',
        ),
        migrations.AddField(
            model_name='model',
            name='picture',
            field=models.ImageField(default='/media/variat/default.png', upload_to='variant'),
        ),
    ]
